env:
  browser: true
  commonjs: true
  es2021: true
extends: 
  #- standard
  - fbjs #se añade conf de facebook
parserOptions:
  ecmaVersion: latest
# agrego regla para cambiar la logitud minima de linea
rules:
  max-len:
    - warn
    - code: 120

